var annotated_dup =
[
    [ "MegaDad", "namespace_mega_dad.html", "namespace_mega_dad" ],
    [ "SuperTiled2Unity", "namespace_super_tiled2_unity.html", "namespace_super_tiled2_unity" ],
    [ "Tests", "namespace_tests.html", "namespace_tests" ],
    [ "Tiled2Unity", "namespace_tiled2_unity.html", "namespace_tiled2_unity" ],
    [ "BusCollide", "class_bus_collide.html", "class_bus_collide" ],
    [ "Camera_Controller", "class_camera___controller.html", "class_camera___controller" ],
    [ "Char2Controller", "class_char2_controller.html", "class_char2_controller" ],
    [ "CharController", "class_char_controller.html", "class_char_controller" ],
    [ "cube", "classcube.html", "classcube" ],
    [ "deleteEnemy", "classdelete_enemy.html", null ],
    [ "FixedJoystick", "class_fixed_joystick.html", "class_fixed_joystick" ],
    [ "FloatingJoystick", "class_floating_joystick.html", "class_floating_joystick" ],
    [ "Joystick", "class_joystick.html", "class_joystick" ],
    [ "MainMenu", "class_main_menu.html", "class_main_menu" ],
    [ "Movement", "class_movement.html", "class_movement" ],
    [ "movement", "classmovement.html", "classmovement" ],
    [ "movement_bus", "classmovement__bus.html", null ],
    [ "movement_cat", "classmovement__cat.html", null ],
    [ "movement_Snowman", "classmovement___snowman.html", null ],
    [ "PauseMenu", "class_pause_menu.html", "class_pause_menu" ],
    [ "PlayerMovement", "class_player_movement.html", "class_player_movement" ],
    [ "PointCalculator", "class_point_calculator.html", "class_point_calculator" ],
    [ "PointCalculatorTests", "class_point_calculator_tests.html", "class_point_calculator_tests" ],
    [ "PrefabSpawner", "class_prefab_spawner.html", null ],
    [ "scr", "classscr.html", null ],
    [ "SetPivot", "class_set_pivot.html", null ],
    [ "Slow_Zone", "class_slow___zone.html", "class_slow___zone" ],
    [ "SortingLayerExposedEditor", "class_sorting_layer_exposed_editor.html", "class_sorting_layer_exposed_editor" ],
    [ "Timer", "class_timer.html", "class_timer" ],
    [ "VariableJoystick", "class_variable_joystick.html", "class_variable_joystick" ]
];